// @RestResource, used for classes only

// URL mapping is relative to:
// https://instance.salesforce.com/services/apexrest/

// the path must begin with '/'

// for a class in namespace 'abc' that is mapped to 'your_url', the API url is:
//  https://instance.salesforce.com/services/apexrest/abc/your_url/


// method level only Rest annotations

// @HttpDelete
// DELETE request sent, deletes the specified source

// @HttpGet
// GET request sent, returns the specified source

// @HttpPatch
// PATCH request sent, updates the specified source

// @HttpPost
// POST request sent, creates a new resource

// @HttpPut
// PUT request sent, creates or updates the specified source
